export type {
  HeaderNavChildItem,
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  FrontmatterPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  TagVocabularyEntry,
} from "./settings-types";
import type {
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  FrontmatterPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
} from "./settings-types";

export const settings = {
  colorScheme: "Default Dark",
  colorMode: {
    defaultMode: "dark",
    lightScheme: "Default Light",
    darkScheme: "Default Dark",
    respectPrefersColorScheme: true,
  } satisfies ColorModeConfig,
  siteName: "Zudo Token Panel",
  siteDescription: "" as string,
  base: "/pj/zdtp/",
  trailingSlash: false as boolean,
  noindex: false as boolean,
  editUrl: false as string | false,
  githubUrl: false as string | false,
  siteUrl: "https://takazudomodular.com/pj/zdtp/" as string,
  docsDir: "src/content/docs",
  defaultLocale: "en" as string,
  locales: {
    ja: { label: "JA", dir: "src/content/docs-ja" },
  } as Record<string, LocaleConfig>,
  mermaid: true,
  sitemap: false,
  docMetainfo: false,
  docTags: false,
  tagPlacement: "after-title" as TagPlacement,
  tagGovernance: "off" as TagGovernanceMode,
  tagVocabulary: false as boolean,
  frontmatterPreview: false as FrontmatterPreviewConfig | false,
  llmsTxt: true,
  math: false,
  cjkFriendly: true as boolean,
  onBrokenMarkdownLinks: "warn" as "warn" | "error" | "ignore",
  aiAssistant: false as boolean,
  docHistory: true,
  bodyFootUtilArea: false as BodyFootUtilAreaConfig | false,
  designTokenPanel: false as boolean,
  colorTweakPanel: undefined as boolean | undefined,
  sidebarResizer: true as boolean,
  sidebarToggle: true as boolean,
  imageEnlarge: false as boolean,
  htmlPreview: undefined as HtmlPreviewConfig | undefined,
  versions: [] as VersionConfig[],
  claudeResources: {
    claudeDir: ".claude",
  } as { claudeDir: string; projectRoot?: string } | false,
  footer: {
    links: [],
    copyright: "Copyright © 2026 Your Name. Built with zudo-doc.",
  } satisfies FooterConfig as FooterConfig | false,
  headerNav: [
    { label: "Getting Started", path: "/docs/getting-started", categoryMatch: "getting-started" },
    { label: "Changelog", path: "/docs/changelog", categoryMatch: "changelog" },
  ] as HeaderNavItem[],
  headerRightItems: [
    { type: "component", component: "version-switcher" },
    { type: "component", component: "github-link" },
    { type: "component", component: "theme-toggle" },
    { type: "component", component: "language-switcher" },
  ] as HeaderRightItem[],
};
