// Generated by scripts/vendor-consumer-manifest.mjs.
// Source: @takazudo/zudo-doc@5.18.0/design-token-panel-config
// Do not edit by hand; rerun the script after intentionally changing the doc dependency.

import type { PanelConfig } from '@takazudo/zdtp';

export const ZUDO_DOC_SOURCE_VERSION = "5.18.0";

export const zudoDocConfigs = {
  "light": {
    "storagePrefix": "zudo-doc-tweak",
    "consoleNamespace": "zudoDoc",
    "modalClassPrefix": "zudo-doc-design-token-panel-modal",
    "schemaId": "zudo-design-tokens/v3",
    "exportFilenameBase": "zudo-doc-design-tokens",
    "tabs": [
      {
        "id": "palette",
        "label": "Palette",
        "tiers": [
          {
            "id": "base",
            "label": "Base",
            "items": [
              {
                "id": "base-0",
                "cssVar": "--palette-base-0",
                "label": "0",
                "default": "oklch(.965 .004 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-1",
                "cssVar": "--palette-base-1",
                "label": "1",
                "default": "oklch(.705 .008 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-2",
                "cssVar": "--palette-base-2",
                "label": "2",
                "default": "oklch(.480 .008 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-3",
                "cssVar": "--palette-base-3",
                "label": "3",
                "default": "oklch(.300 .006 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-4",
                "cssVar": "--palette-base-4",
                "label": "4",
                "default": "oklch(.185 .005 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          },
          {
            "id": "accent",
            "label": "Accent",
            "items": [
              {
                "id": "accent-0",
                "cssVar": "--palette-accent-0",
                "label": "0",
                "default": "oklch(.755 .130 64)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent-1",
                "cssVar": "--palette-accent-1",
                "label": "1",
                "default": "oklch(.700 .158 62)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent-2",
                "cssVar": "--palette-accent-2",
                "label": "2",
                "default": "oklch(.470 .120 56)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          },
          {
            "id": "state",
            "label": "State",
            "items": [
              {
                "id": "state-danger",
                "cssVar": "--palette-state-danger",
                "label": "danger",
                "default": "oklch(.640 .170 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-success",
                "cssVar": "--palette-state-success",
                "label": "success",
                "default": "oklch(.680 .145 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-warning",
                "cssVar": "--palette-state-warning",
                "label": "warning",
                "default": "oklch(.760 .135 82)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-info",
                "cssVar": "--palette-state-info",
                "label": "info",
                "default": "oklch(.680 .130 245)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          }
        ]
      },
      {
        "id": "color",
        "label": "Color",
        "tiers": [
          {
            "id": "semantic",
            "label": "Semantic",
            "semantic": true,
            "referencesRamps": [
              {
                "tab": "palette",
                "tier": "base"
              },
              {
                "tab": "palette",
                "tier": "accent"
              },
              {
                "tab": "palette",
                "tier": "state"
              }
            ],
            "items": [
              {
                "id": "bg",
                "cssVar": "--zd-bg",
                "label": "bg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "fg",
                "cssVar": "--zd-fg",
                "label": "fg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "selection-bg",
                "cssVar": "--zd-selection-bg",
                "label": "selection-bg",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "selection-fg",
                "cssVar": "--zd-selection-fg",
                "label": "selection-fg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "surface",
                "cssVar": "--zd-surface",
                "label": "surface",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "muted",
                "cssVar": "--zd-muted",
                "label": "muted",
                "default": "base:base-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent",
                "cssVar": "--zd-accent",
                "label": "accent",
                "default": "accent:accent-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accentHover",
                "cssVar": "--zd-accent-hover",
                "label": "accentHover",
                "default": "oklch(.400 .096 56)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "codeBg",
                "cssVar": "--zd-code-bg",
                "label": "codeBg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "codeFg",
                "cssVar": "--zd-code-fg",
                "label": "codeFg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "success",
                "cssVar": "--zd-success",
                "label": "success",
                "default": "oklch(.470 .140 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "danger",
                "cssVar": "--zd-danger",
                "label": "danger",
                "default": "oklch(.505 .170 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "warning",
                "cssVar": "--zd-warning",
                "label": "warning",
                "default": "oklch(.490 .100 82)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "info",
                "cssVar": "--zd-info",
                "label": "info",
                "default": "oklch(.485 .122 245)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidNodeBg",
                "cssVar": "--zd-mermaid-node-bg",
                "label": "mermaidNodeBg",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidText",
                "cssVar": "--zd-mermaid-text",
                "label": "mermaidText",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidLine",
                "cssVar": "--zd-mermaid-line",
                "label": "mermaidLine",
                "default": "base:base-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidLabelBg",
                "cssVar": "--zd-mermaid-label-bg",
                "label": "mermaidLabelBg",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidNoteBg",
                "cssVar": "--zd-mermaid-note-bg",
                "label": "mermaidNoteBg",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatUserBg",
                "cssVar": "--zd-chat-user-bg",
                "label": "chatUserBg",
                "default": "accent:accent-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatUserText",
                "cssVar": "--zd-chat-user-text",
                "label": "chatUserText",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatAssistantBg",
                "cssVar": "--zd-chat-assistant-bg",
                "label": "chatAssistantBg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatAssistantText",
                "cssVar": "--zd-chat-assistant-text",
                "label": "chatAssistantText",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "imageOverlayBg",
                "cssVar": "--zd-image-overlay-bg",
                "label": "imageOverlayBg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "imageOverlayFg",
                "cssVar": "--zd-image-overlay-fg",
                "label": "imageOverlayFg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "matchedKeywordBg",
                "cssVar": "--zd-matched-keyword-bg",
                "label": "matchedKeywordBg",
                "default": "oklch(.700 .158 62)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "matchedKeywordFg",
                "cssVar": "--zd-matched-keyword-fg",
                "label": "matchedKeywordFg",
                "default": "oklch(.300 .003 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxComment",
                "cssVar": "--zd-syntax-comment",
                "label": "syntaxComment",
                "default": "base:base-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxString",
                "cssVar": "--zd-syntax-string",
                "label": "syntaxString",
                "default": "oklch(.470 .140 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxNumber",
                "cssVar": "--zd-syntax-number",
                "label": "syntaxNumber",
                "default": "oklch(.490 .100 82)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxKeyword",
                "cssVar": "--zd-syntax-keyword",
                "label": "syntaxKeyword",
                "default": "accent:accent-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxCallable",
                "cssVar": "--zd-syntax-callable",
                "label": "syntaxCallable",
                "default": "oklch(.485 .122 245)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxType",
                "cssVar": "--zd-syntax-type",
                "label": "syntaxType",
                "default": "oklch(.490 .100 82)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxName",
                "cssVar": "--zd-syntax-name",
                "label": "syntaxName",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxInserted",
                "cssVar": "--zd-syntax-inserted",
                "label": "syntaxInserted",
                "default": "oklch(.460 .140 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxDeleted",
                "cssVar": "--zd-syntax-deleted",
                "label": "syntaxDeleted",
                "default": "oklch(.490 .170 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          }
        ],
        "colorExtras": {
          "id": "zudo-doc",
          "label": "Zudo Doc",
          "baseRoles": {},
          "baseDefaults": {},
          "defaultShikiTheme": "github-dark",
          "colorSchemes": {},
          "panelSettings": {
            "colorScheme": "Default Light",
            "colorMode": {
              "defaultMode": "light",
              "lightScheme": "Default Light",
              "darkScheme": "Default Dark"
            }
          }
        }
      },
      {
        "id": "font",
        "label": "Font",
        "tiers": [
          {
            "id": "font-scale",
            "label": "Scale",
            "items": [
              {
                "id": "text-scale-2xs",
                "cssVar": "--text-scale-2xs",
                "label": "text-scale-2xs",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-xs",
                "cssVar": "--text-scale-xs",
                "label": "text-scale-xs",
                "default": "0.875rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-sm",
                "cssVar": "--text-scale-sm",
                "label": "text-scale-sm",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-md",
                "cssVar": "--text-scale-md",
                "label": "text-scale-md",
                "default": "1.2rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-lg",
                "cssVar": "--text-scale-lg",
                "label": "text-scale-lg",
                "default": "1.4rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-xl",
                "cssVar": "--text-scale-xl",
                "label": "text-scale-xl",
                "default": "3rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-2xl",
                "cssVar": "--text-scale-2xl",
                "label": "text-scale-2xl",
                "default": "3.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "preview": "size"
          },
          {
            "id": "font-size",
            "label": "Font size",
            "items": [
              {
                "id": "text-micro",
                "cssVar": "--text-micro",
                "label": "text-micro",
                "default": "text-scale-2xs",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-caption",
                "cssVar": "--text-caption",
                "label": "text-caption",
                "default": "text-scale-xs",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-small",
                "cssVar": "--text-small",
                "label": "text-small",
                "default": "text-scale-sm",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-body",
                "cssVar": "--text-body",
                "label": "text-body",
                "default": "text-scale-md",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-title",
                "cssVar": "--text-title",
                "label": "text-title",
                "default": "text-scale-lg",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-heading",
                "cssVar": "--text-heading",
                "label": "text-heading",
                "default": "text-scale-xl",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-display",
                "cssVar": "--text-display",
                "label": "text-display",
                "default": "text-scale-2xl",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "referencesTier": "font-scale"
          },
          {
            "id": "line-height",
            "label": "Line height",
            "items": [
              {
                "id": "leading-tight",
                "cssVar": "--leading-tight",
                "label": "leading-tight",
                "default": "1.25",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-snug",
                "cssVar": "--leading-snug",
                "label": "leading-snug",
                "default": "1.375",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-normal",
                "cssVar": "--leading-normal",
                "label": "leading-normal",
                "default": "1.5",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-relaxed",
                "cssVar": "--leading-relaxed",
                "label": "leading-relaxed",
                "default": "1.625",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              }
            ],
            "preview": "line-height",
            "previewBase": "--text-scale-md"
          },
          {
            "id": "font-weight",
            "label": "Font weight",
            "items": [
              {
                "id": "font-weight-normal",
                "cssVar": "--font-weight-normal",
                "label": "font-weight-normal",
                "default": "400",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-medium",
                "cssVar": "--font-weight-medium",
                "label": "font-weight-medium",
                "default": "500",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-semibold",
                "cssVar": "--font-weight-semibold",
                "label": "font-weight-semibold",
                "default": "600",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-bold",
                "cssVar": "--font-weight-bold",
                "label": "font-weight-bold",
                "default": "700",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              }
            ],
            "preview": "weight"
          },
          {
            "id": "font-family",
            "label": "Font family",
            "items": [
              {
                "id": "font-sans",
                "cssVar": "--font-sans",
                "label": "font-sans",
                "default": "system-ui, sans-serif",
                "type": {
                  "kind": "text"
                }
              },
              {
                "id": "font-mono",
                "cssVar": "--font-mono",
                "label": "font-mono",
                "default": "ui-monospace, monospace",
                "type": {
                  "kind": "text"
                }
              }
            ],
            "preview": "family"
          }
        ]
      },
      {
        "id": "spacing",
        "label": "Spacing",
        "tiers": [
          {
            "id": "hsp",
            "label": "Horizontal spacing",
            "items": [
              {
                "id": "hsp-2xs",
                "cssVar": "--spacing-hsp-2xs",
                "label": "hsp-2xs",
                "default": "0.125rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-xs",
                "cssVar": "--spacing-hsp-xs",
                "label": "hsp-xs",
                "default": "0.375rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-sm",
                "cssVar": "--spacing-hsp-sm",
                "label": "hsp-sm",
                "default": "0.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-md",
                "cssVar": "--spacing-hsp-md",
                "label": "hsp-md",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-lg",
                "cssVar": "--spacing-hsp-lg",
                "label": "hsp-lg",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-xl",
                "cssVar": "--spacing-hsp-xl",
                "label": "hsp-xl",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-2xl",
                "cssVar": "--spacing-hsp-2xl",
                "label": "hsp-2xl",
                "default": "2rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "vsp",
            "label": "Vertical spacing",
            "items": [
              {
                "id": "vsp-3xs",
                "cssVar": "--spacing-vsp-3xs",
                "label": "vsp-3xs",
                "default": "0.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-2xs",
                "cssVar": "--spacing-vsp-2xs",
                "label": "vsp-2xs",
                "default": "0.4375rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-xs",
                "cssVar": "--spacing-vsp-xs",
                "label": "vsp-xs",
                "default": "0.875rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-sm",
                "cssVar": "--spacing-vsp-sm",
                "label": "vsp-sm",
                "default": "1.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-md",
                "cssVar": "--spacing-vsp-md",
                "label": "vsp-md",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-lg",
                "cssVar": "--spacing-vsp-lg",
                "label": "vsp-lg",
                "default": "1.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-xl",
                "cssVar": "--spacing-vsp-xl",
                "label": "vsp-xl",
                "default": "2.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-2xl",
                "cssVar": "--spacing-vsp-2xl",
                "label": "vsp-2xl",
                "default": "3.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "icon",
            "label": "Icons",
            "items": [
              {
                "id": "icon-xs",
                "cssVar": "--spacing-icon-xs",
                "label": "icon-xs",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-sm",
                "cssVar": "--spacing-icon-sm",
                "label": "icon-sm",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-md",
                "cssVar": "--spacing-icon-md",
                "label": "icon-md",
                "default": "1.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-lg",
                "cssVar": "--spacing-icon-lg",
                "label": "icon-lg",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "layout",
            "label": "Layout",
            "items": [
              {
                "id": "image-overlay-inset",
                "cssVar": "--spacing-image-overlay-inset",
                "label": "image-overlay-inset",
                "default": "0.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "spacing-0",
                "cssVar": "--spacing-0",
                "label": "spacing-0",
                "default": "0",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": ""
                },
                "readonly": true
              },
              {
                "id": "spacing-px",
                "cssVar": "--spacing-px",
                "label": "spacing-px",
                "default": "1px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                },
                "readonly": true
              },
              {
                "id": "sidebar-w",
                "cssVar": "--zd-sidebar-w",
                "label": "sidebar-w",
                "default": "clamp(14rem, 20vw, 22rem)",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": ""
                },
                "readonly": true
              }
            ]
          }
        ]
      },
      {
        "id": "size",
        "label": "Size",
        "tiers": [
          {
            "id": "radius",
            "label": "Radius",
            "items": [
              {
                "id": "radius-DEFAULT",
                "cssVar": "--radius-DEFAULT",
                "label": "radius-DEFAULT",
                "default": "4px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                }
              },
              {
                "id": "radius-lg",
                "cssVar": "--radius-lg",
                "label": "radius-lg",
                "default": "8px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                }
              },
              {
                "id": "radius-full",
                "cssVar": "--radius-full",
                "label": "radius-full",
                "default": "9999px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                },
                "pill": {
                  "value": "9999px",
                  "customDefault": "16px"
                }
              }
            ],
            "preview": "radius"
          },
          {
            "id": "transition",
            "label": "Transition",
            "items": [
              {
                "id": "default-transition-duration",
                "cssVar": "--default-transition-duration",
                "label": "default-transition-duration",
                "default": "150ms",
                "type": {
                  "kind": "length",
                  "step": 10,
                  "unit": "ms"
                }
              }
            ],
            "preview": "duration"
          }
        ]
      }
    ]
  },
  "dark": {
    "storagePrefix": "zudo-doc-tweak",
    "consoleNamespace": "zudoDoc",
    "modalClassPrefix": "zudo-doc-design-token-panel-modal",
    "schemaId": "zudo-design-tokens/v3",
    "exportFilenameBase": "zudo-doc-design-tokens",
    "tabs": [
      {
        "id": "palette",
        "label": "Palette",
        "tiers": [
          {
            "id": "base",
            "label": "Base",
            "items": [
              {
                "id": "base-0",
                "cssVar": "--palette-base-0",
                "label": "0",
                "default": "oklch(.965 .004 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-1",
                "cssVar": "--palette-base-1",
                "label": "1",
                "default": "oklch(.705 .008 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-2",
                "cssVar": "--palette-base-2",
                "label": "2",
                "default": "oklch(.480 .008 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-3",
                "cssVar": "--palette-base-3",
                "label": "3",
                "default": "oklch(.300 .006 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "base-4",
                "cssVar": "--palette-base-4",
                "label": "4",
                "default": "oklch(.185 .005 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          },
          {
            "id": "accent",
            "label": "Accent",
            "items": [
              {
                "id": "accent-0",
                "cssVar": "--palette-accent-0",
                "label": "0",
                "default": "oklch(.755 .130 64)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent-1",
                "cssVar": "--palette-accent-1",
                "label": "1",
                "default": "oklch(.700 .158 62)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent-2",
                "cssVar": "--palette-accent-2",
                "label": "2",
                "default": "oklch(.470 .120 56)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          },
          {
            "id": "state",
            "label": "State",
            "items": [
              {
                "id": "state-danger",
                "cssVar": "--palette-state-danger",
                "label": "danger",
                "default": "oklch(.640 .170 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-success",
                "cssVar": "--palette-state-success",
                "label": "success",
                "default": "oklch(.680 .145 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-warning",
                "cssVar": "--palette-state-warning",
                "label": "warning",
                "default": "oklch(.760 .135 82)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "state-info",
                "cssVar": "--palette-state-info",
                "label": "info",
                "default": "oklch(.680 .130 245)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          }
        ]
      },
      {
        "id": "color",
        "label": "Color",
        "tiers": [
          {
            "id": "semantic",
            "label": "Semantic",
            "semantic": true,
            "referencesRamps": [
              {
                "tab": "palette",
                "tier": "base"
              },
              {
                "tab": "palette",
                "tier": "accent"
              },
              {
                "tab": "palette",
                "tier": "state"
              }
            ],
            "items": [
              {
                "id": "bg",
                "cssVar": "--zd-bg",
                "label": "bg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "fg",
                "cssVar": "--zd-fg",
                "label": "fg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "selection-bg",
                "cssVar": "--zd-selection-bg",
                "label": "selection-bg",
                "default": "base:base-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "selection-fg",
                "cssVar": "--zd-selection-fg",
                "label": "selection-fg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "surface",
                "cssVar": "--zd-surface",
                "label": "surface",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "muted",
                "cssVar": "--zd-muted",
                "label": "muted",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accent",
                "cssVar": "--zd-accent",
                "label": "accent",
                "default": "accent:accent-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "accentHover",
                "cssVar": "--zd-accent-hover",
                "label": "accentHover",
                "default": "accent:accent-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "codeBg",
                "cssVar": "--zd-code-bg",
                "label": "codeBg",
                "default": "base:base-3",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "codeFg",
                "cssVar": "--zd-code-fg",
                "label": "codeFg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "success",
                "cssVar": "--zd-success",
                "label": "success",
                "default": "state:state-success",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "danger",
                "cssVar": "--zd-danger",
                "label": "danger",
                "default": "oklch(.655 .170 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "warning",
                "cssVar": "--zd-warning",
                "label": "warning",
                "default": "state:state-warning",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "info",
                "cssVar": "--zd-info",
                "label": "info",
                "default": "state:state-info",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidNodeBg",
                "cssVar": "--zd-mermaid-node-bg",
                "label": "mermaidNodeBg",
                "default": "base:base-3",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidText",
                "cssVar": "--zd-mermaid-text",
                "label": "mermaidText",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidLine",
                "cssVar": "--zd-mermaid-line",
                "label": "mermaidLine",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidLabelBg",
                "cssVar": "--zd-mermaid-label-bg",
                "label": "mermaidLabelBg",
                "default": "base:base-3",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "mermaidNoteBg",
                "cssVar": "--zd-mermaid-note-bg",
                "label": "mermaidNoteBg",
                "default": "base:base-2",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatUserBg",
                "cssVar": "--zd-chat-user-bg",
                "label": "chatUserBg",
                "default": "accent:accent-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatUserText",
                "cssVar": "--zd-chat-user-text",
                "label": "chatUserText",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatAssistantBg",
                "cssVar": "--zd-chat-assistant-bg",
                "label": "chatAssistantBg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "chatAssistantText",
                "cssVar": "--zd-chat-assistant-text",
                "label": "chatAssistantText",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "imageOverlayBg",
                "cssVar": "--zd-image-overlay-bg",
                "label": "imageOverlayBg",
                "default": "base:base-4",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "imageOverlayFg",
                "cssVar": "--zd-image-overlay-fg",
                "label": "imageOverlayFg",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "matchedKeywordBg",
                "cssVar": "--zd-matched-keyword-bg",
                "label": "matchedKeywordBg",
                "default": "oklch(.700 .158 62)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "matchedKeywordFg",
                "cssVar": "--zd-matched-keyword-fg",
                "label": "matchedKeywordFg",
                "default": "oklch(.300 .003 65)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxComment",
                "cssVar": "--zd-syntax-comment",
                "label": "syntaxComment",
                "default": "base:base-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxString",
                "cssVar": "--zd-syntax-string",
                "label": "syntaxString",
                "default": "state:state-success",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxNumber",
                "cssVar": "--zd-syntax-number",
                "label": "syntaxNumber",
                "default": "state:state-warning",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxKeyword",
                "cssVar": "--zd-syntax-keyword",
                "label": "syntaxKeyword",
                "default": "accent:accent-1",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxCallable",
                "cssVar": "--zd-syntax-callable",
                "label": "syntaxCallable",
                "default": "state:state-info",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxType",
                "cssVar": "--zd-syntax-type",
                "label": "syntaxType",
                "default": "state:state-warning",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxName",
                "cssVar": "--zd-syntax-name",
                "label": "syntaxName",
                "default": "base:base-0",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxInserted",
                "cssVar": "--zd-syntax-inserted",
                "label": "syntaxInserted",
                "default": "oklch(.750 .145 145)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              },
              {
                "id": "syntaxDeleted",
                "cssVar": "--zd-syntax-deleted",
                "label": "syntaxDeleted",
                "default": "oklch(.820 .100 25)",
                "type": {
                  "kind": "color",
                  "format": "oklch"
                }
              }
            ]
          }
        ],
        "colorExtras": {
          "id": "zudo-doc",
          "label": "Zudo Doc",
          "baseRoles": {},
          "baseDefaults": {},
          "defaultShikiTheme": "github-dark",
          "colorSchemes": {},
          "panelSettings": {
            "colorScheme": "Default Dark",
            "colorMode": {
              "defaultMode": "dark",
              "lightScheme": "Default Light",
              "darkScheme": "Default Dark"
            }
          }
        }
      },
      {
        "id": "font",
        "label": "Font",
        "tiers": [
          {
            "id": "font-scale",
            "label": "Scale",
            "items": [
              {
                "id": "text-scale-2xs",
                "cssVar": "--text-scale-2xs",
                "label": "text-scale-2xs",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-xs",
                "cssVar": "--text-scale-xs",
                "label": "text-scale-xs",
                "default": "0.875rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-sm",
                "cssVar": "--text-scale-sm",
                "label": "text-scale-sm",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-md",
                "cssVar": "--text-scale-md",
                "label": "text-scale-md",
                "default": "1.2rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-lg",
                "cssVar": "--text-scale-lg",
                "label": "text-scale-lg",
                "default": "1.4rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-xl",
                "cssVar": "--text-scale-xl",
                "label": "text-scale-xl",
                "default": "3rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-scale-2xl",
                "cssVar": "--text-scale-2xl",
                "label": "text-scale-2xl",
                "default": "3.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "preview": "size"
          },
          {
            "id": "font-size",
            "label": "Font size",
            "items": [
              {
                "id": "text-micro",
                "cssVar": "--text-micro",
                "label": "text-micro",
                "default": "text-scale-2xs",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-caption",
                "cssVar": "--text-caption",
                "label": "text-caption",
                "default": "text-scale-xs",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-small",
                "cssVar": "--text-small",
                "label": "text-small",
                "default": "text-scale-sm",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-body",
                "cssVar": "--text-body",
                "label": "text-body",
                "default": "text-scale-md",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-title",
                "cssVar": "--text-title",
                "label": "text-title",
                "default": "text-scale-lg",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-heading",
                "cssVar": "--text-heading",
                "label": "text-heading",
                "default": "text-scale-xl",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "text-display",
                "cssVar": "--text-display",
                "label": "text-display",
                "default": "text-scale-2xl",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "referencesTier": "font-scale"
          },
          {
            "id": "line-height",
            "label": "Line height",
            "items": [
              {
                "id": "leading-tight",
                "cssVar": "--leading-tight",
                "label": "leading-tight",
                "default": "1.25",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-snug",
                "cssVar": "--leading-snug",
                "label": "leading-snug",
                "default": "1.375",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-normal",
                "cssVar": "--leading-normal",
                "label": "leading-normal",
                "default": "1.5",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              },
              {
                "id": "leading-relaxed",
                "cssVar": "--leading-relaxed",
                "label": "leading-relaxed",
                "default": "1.625",
                "type": {
                  "kind": "number",
                  "step": 0.05,
                  "unit": ""
                }
              }
            ],
            "preview": "line-height",
            "previewBase": "--text-scale-md"
          },
          {
            "id": "font-weight",
            "label": "Font weight",
            "items": [
              {
                "id": "font-weight-normal",
                "cssVar": "--font-weight-normal",
                "label": "font-weight-normal",
                "default": "400",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-medium",
                "cssVar": "--font-weight-medium",
                "label": "font-weight-medium",
                "default": "500",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-semibold",
                "cssVar": "--font-weight-semibold",
                "label": "font-weight-semibold",
                "default": "600",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              },
              {
                "id": "font-weight-bold",
                "cssVar": "--font-weight-bold",
                "label": "font-weight-bold",
                "default": "700",
                "type": {
                  "kind": "select",
                  "options": [
                    "100",
                    "200",
                    "300",
                    "400",
                    "500",
                    "600",
                    "700",
                    "800",
                    "900"
                  ]
                }
              }
            ],
            "preview": "weight"
          },
          {
            "id": "font-family",
            "label": "Font family",
            "items": [
              {
                "id": "font-sans",
                "cssVar": "--font-sans",
                "label": "font-sans",
                "default": "system-ui, sans-serif",
                "type": {
                  "kind": "text"
                }
              },
              {
                "id": "font-mono",
                "cssVar": "--font-mono",
                "label": "font-mono",
                "default": "ui-monospace, monospace",
                "type": {
                  "kind": "text"
                }
              }
            ],
            "preview": "family"
          }
        ]
      },
      {
        "id": "spacing",
        "label": "Spacing",
        "tiers": [
          {
            "id": "hsp",
            "label": "Horizontal spacing",
            "items": [
              {
                "id": "hsp-2xs",
                "cssVar": "--spacing-hsp-2xs",
                "label": "hsp-2xs",
                "default": "0.125rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-xs",
                "cssVar": "--spacing-hsp-xs",
                "label": "hsp-xs",
                "default": "0.375rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-sm",
                "cssVar": "--spacing-hsp-sm",
                "label": "hsp-sm",
                "default": "0.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-md",
                "cssVar": "--spacing-hsp-md",
                "label": "hsp-md",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-lg",
                "cssVar": "--spacing-hsp-lg",
                "label": "hsp-lg",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-xl",
                "cssVar": "--spacing-hsp-xl",
                "label": "hsp-xl",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "hsp-2xl",
                "cssVar": "--spacing-hsp-2xl",
                "label": "hsp-2xl",
                "default": "2rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "vsp",
            "label": "Vertical spacing",
            "items": [
              {
                "id": "vsp-3xs",
                "cssVar": "--spacing-vsp-3xs",
                "label": "vsp-3xs",
                "default": "0.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-2xs",
                "cssVar": "--spacing-vsp-2xs",
                "label": "vsp-2xs",
                "default": "0.4375rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-xs",
                "cssVar": "--spacing-vsp-xs",
                "label": "vsp-xs",
                "default": "0.875rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-sm",
                "cssVar": "--spacing-vsp-sm",
                "label": "vsp-sm",
                "default": "1.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-md",
                "cssVar": "--spacing-vsp-md",
                "label": "vsp-md",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-lg",
                "cssVar": "--spacing-vsp-lg",
                "label": "vsp-lg",
                "default": "1.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-xl",
                "cssVar": "--spacing-vsp-xl",
                "label": "vsp-xl",
                "default": "2.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              },
              {
                "id": "vsp-2xl",
                "cssVar": "--spacing-vsp-2xl",
                "label": "vsp-2xl",
                "default": "3.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.025,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "icon",
            "label": "Icons",
            "items": [
              {
                "id": "icon-xs",
                "cssVar": "--spacing-icon-xs",
                "label": "icon-xs",
                "default": "0.75rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-sm",
                "cssVar": "--spacing-icon-sm",
                "label": "icon-sm",
                "default": "1rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-md",
                "cssVar": "--spacing-icon-md",
                "label": "icon-md",
                "default": "1.25rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "icon-lg",
                "cssVar": "--spacing-icon-lg",
                "label": "icon-lg",
                "default": "1.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              }
            ],
            "preview": "bar"
          },
          {
            "id": "layout",
            "label": "Layout",
            "items": [
              {
                "id": "image-overlay-inset",
                "cssVar": "--spacing-image-overlay-inset",
                "label": "image-overlay-inset",
                "default": "0.5rem",
                "type": {
                  "kind": "length",
                  "step": 0.05,
                  "unit": "rem"
                }
              },
              {
                "id": "spacing-0",
                "cssVar": "--spacing-0",
                "label": "spacing-0",
                "default": "0",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": ""
                },
                "readonly": true
              },
              {
                "id": "spacing-px",
                "cssVar": "--spacing-px",
                "label": "spacing-px",
                "default": "1px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                },
                "readonly": true
              },
              {
                "id": "sidebar-w",
                "cssVar": "--zd-sidebar-w",
                "label": "sidebar-w",
                "default": "clamp(14rem, 20vw, 22rem)",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": ""
                },
                "readonly": true
              }
            ]
          }
        ]
      },
      {
        "id": "size",
        "label": "Size",
        "tiers": [
          {
            "id": "radius",
            "label": "Radius",
            "items": [
              {
                "id": "radius-DEFAULT",
                "cssVar": "--radius-DEFAULT",
                "label": "radius-DEFAULT",
                "default": "4px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                }
              },
              {
                "id": "radius-lg",
                "cssVar": "--radius-lg",
                "label": "radius-lg",
                "default": "8px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                }
              },
              {
                "id": "radius-full",
                "cssVar": "--radius-full",
                "label": "radius-full",
                "default": "9999px",
                "type": {
                  "kind": "length",
                  "step": 1,
                  "unit": "px"
                },
                "pill": {
                  "value": "9999px",
                  "customDefault": "16px"
                }
              }
            ],
            "preview": "radius"
          },
          {
            "id": "transition",
            "label": "Transition",
            "items": [
              {
                "id": "default-transition-duration",
                "cssVar": "--default-transition-duration",
                "label": "default-transition-duration",
                "default": "150ms",
                "type": {
                  "kind": "length",
                  "step": 10,
                  "unit": "ms"
                }
              }
            ],
            "preview": "duration"
          }
        ]
      }
    ]
  }
} as const satisfies Record<'light' | 'dark', PanelConfig>;
